Support discourse 的获取
oss-know/airflow-jobs pull request #152
Opened 2023-02-15 07:22 UTC by ckxkexing

dags/oss_know/libs/clickhouse/init_ck_transfer_data.py 

文件修改较大，帮忙看看怎么合并

2023-02-16 07:14 UTC, ckxkexing commented
稍等，我在rust上确认一遍

2023-02-22 04:42 UTC, ckxkexing commented
lgtm

2023-03-02 03:17 UTC, crystaldust requested changes

2023-03-02 03:17 UTC, crystaldust commented on dags/oss_know/libs/discourse/crawl_topic_content.py
> +def get_data_from_opensearch(index, owner, repo, opensearch_conn_datas):
功能相同的方法可以抽取到utils/discourse.py中，成为一个工具函数，在其他爬取数据的地方调用。

2023-03-02 03:17 UTC, crystaldust commented on dags/oss_know/libs/discourse/crawl_topic_content.py
> +def get_api(url, session):
get_api可以提取成一个工具函数，放在utils/discourse.py提供调用

2023-03-02 03:17 UTC, crystaldust commented on dags/oss_know/libs/discourse/crawl_topic_content.py
> +                    print(f"ERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRROR!!! {url}")
使用logger.error替代print。logger统一从utils/log/logger.py获取

2023-03-07 06:27 UTC, merged